from recbole.model.sequential_recommender.gru4rec import GRU4Rec
from recbole.model.sequential_recommender.fearec import FEARec
from recbole.model.sequential_recommender.sasrec import SASRec
from recbole.model.sequential_recommender.bsarec import BSARec
from recbole.model.sequential_recommender.fearec import FEARec
from recbole.model.sequential_recommender.recblr import RecBLR
from recbole.model.sequential_recommender.indirec import InDiRec
from recbole.model.sequential_recommender.duorec import DuoRec
from recbole.model.sequential_recommender.mamba4rec import Mamba4Rec
from recbole.model.sequential_recommender.linrec import LinRec
from recbole.model.sequential_recommender.muffin import Muffin
from recbole.model.sequential_recommender.starrec import STARRec
from recbole.model.sequential_recommender.glintru import GLINTRU
from recbole.model.sequential_recommender.tvrec import TVRec
from recbole.model.sequential_recommender.fmlprec import FMLPRec
from recbole.model.sequential_recommender.sigma import SIGMA
from recbole.model.sequential_recommender.telarec import TelaRec